package com.jivesoftware.os.miru.siphon.deployable.topics;

/**
 * Created by jonathan.colt on 11/17/16.
 */
public class ActivityNames {

    public static final String[] list = {
        "Basketball",
        "Beach Volleyball",
        "Biking",
        "Boot Camp",
        "Calisthenics",
        "Chopping / Stacking Firewood",
        "Circuit Training",
        "Dance Revolution",
        "Elliptical Trainer",
        "Family Hike",
        "Field Hockey",
        "Flag Football",
        "Football",
        "Half Marathon",
        "Handball",
        "Hockey",
        "Ice Hockey",
        "Ice Skating",
        "In-line Skating",
        "Irish Dancing",
        "Jazzercise",
        "Jogging",
        "Judo",
        "Jujitsu",
        "Jump Rope",
        "Lacrosse",
        "Line Dancing",
        "Marathon",
        "Nordic Track",
        "Pilates",
        "Pull ups / Push ups",
        "Racquetball",
        "Rapelling",
        "Rock Climbing",
        "Roller Hockey",
        "Roller Skating",
        "Rollerblading",
        "Rowing",
        "Running",
        "Shovel Snow",
        "Sit Ups",
        "Snowshoeing",
        "Soccer",
        "Speed Skating",
        "Spinning Class",
        "Stair Step Machine",
        "Step Aerobics",
        "Street Hockey",
        "Surfing",
        "Swimming Laps",
        "Tae Bo",
        "Taekwondo",
        "Take an Aerobics Class Together",
        "Take the Stairs",
        "Tap Dancing",
        "Tennis",
        "Track & Field",
        "Triathlon",
        "Tumbling",
        "Ultimate Frisbee",
        "Zumba Class",
        "Back Packing",
        "Badminton",
        "Ballet",
        "Baseball",
        "Canoeing",
        "Capture the Flag",
        "Cheerleading",
        "Cut the Grass",
        "Dancing",
        "Exercise as a Family",
        "Exercise Bike",
        "Family Hour at the Fitness Center",
        "Family Walk",
        "Four Square",
        "Frisbee",
        "Frisbee Golf",
        "Fun Run",
        "Golf",
        "Gymnastics",
        "Hide and Seek",
        "Horseback Riding",
        "Karate",
        "Kayaking",
        "Kick Ball",
        "Kick the Can",
        "Knee boarding",
        "Line Dancing",
        "Mow the lawn",
        "Paint the house, fence",
        "Paintball",
        "Play Catch",
        "Playing in the Snow",
        "Rake the lawn",
        "Rake the leaves",
        "Skateboarding",
        "Skiing",
        "Sledding",
        "Snorkeling",
        "Snow Boarding",
        "Softball",
        "Stationary Bike",
        "Swimming",
        "Tag",
        "Tai Chi",
        "T-ball",
        "Tetherball",
        "Throw Frisbee",
        "Treadmill",
        "Vacuum",
        "Visit a Theme Park",
        "Volksmarch",
        "Volleyball",
        "Wake Boarding",
        "Walk 10,000 Steps a Day",
        "Walking",
        "Wash the car",
        "Water Aerobics",
        "Water Skiing",
        "Wax the car",
        "Weight Lifting",
        "Weight Training",
        "White Water Rafting",
        "Wiffle Ball",
        "Wii Fit",
        "Yoga",
        "Air Hockey",
        "Bocce Ball",
        "Bowling",
        "Camping",
        "Clean the house",
        "Clean the pool",
        "Community Service Projects",
        "Cricket",
        "Croquet",
        "Cup Stacking",
        "Daddy and Me class",
        "Detail / Vacuum the car",
        "Dust the furniture",
        "Fishing",
        "Fly a Kite",
        "Foosball",
        "Folding Clothes",
        "Gardening",
        "Geocaching",
        "Golf Lessons",
        "Hopscotch",
        "Horseshoes",
        "House Cleaning",
        "Household Chores",
        "Hula Hoop",
        "Jumping Jacks",
        "Limbo",
        "Make a Snowman",
        "Make Sandcastles",
        "Mini-Golf",
        "Mommy and Me class",
        "Paddle boating",
        "Ping Pong",
        "Plan and Take a Day Trip",
        "Plant a Tree",
        "Plant Flowers",
        "Play Musical Instrument",
        "Pogo Sticks",
        "Pool",
        "Run through Sprinkler",
        "Sailing",
        "Science Experiments",
        "Scuba Diving",
        "Shopping",
        "Shuffle Board",
        "Stretching",
        "Sweep Floor/Garage",
        "Table Tennis",
        "Taiko Drumming",
        "Target Shooting",
        "Theatre Rehearsal",
        "Trampoline",
        "Vegetable Gardening",
        "Visit a Museum",
        "Walk the dog",
        "Walk the Mall",
        "Wash Clothes",
        "Wash the dishes",
        "Wash the dog",
        "Water the Plants",
        "Weed the garden",
        "Yard Work"
    };

}
