package com.jivesoftware.os.miru.siphon.deployable.topics;

/**
 * Created by jonathan.colt on 11/17/16.
 */
public class TopicNames {
    public static final String[] list = {
        "Activism",
        "Adventure",
        "Advertising",
        "Africa",
        "Aging",
        "Agriculture",
        "AI",
        "AIDS",
        "Aircraft",
        "Algorithm",
        "Alternative energy",
        "Ancient world",
        "Animals",
        "Animation",
        "Anthropocene",
        "Anthropology",
        "Ants",
        "Apes",
        "Archaeology",
        "Architecture",
        "Art",
        "Arts",
        "Asia",
        "Astronomy",
        "Atheism",
        "Augmented reality",
        "Autism spectrum disorder",
        "Bacteria",
        "Beauty",
        "Bees",
        "Behavioral economics",
        "Big bang",
        "Big problems",
        "Biodiversity",
        "Bioethics",
        "Biology",
        "Biomechanics",
        "Biomimicry",
        "Biotech",
        "Birds",
        "Blockchain",
        "Body language",
        "Books",
        "Botany",
        "Brain",
        "Brand",
        "Brazil",
        "Buddhism",
        "Bullying",
        "Business",
        "Cancer",
        "Capitalism",
        "Cars",
        "Cello",
        "Charter for compassion",
        "Chemistry",
        "Children",
        "China",
        "Choice",
        "Christianity",
        "Cities",
        "Climate change",
        "Cloud",
        "Code",
        "Cognitive science",
        "Collaboration",
        "Comedy",
        "Communication",
        "Community",
        "Compassion",
        "Complexity",
        "Composing",
        "Computers",
        "Conducting",
        "Consciousness",
        "Conservation",
        "Consumerism",
        "Corruption",
        "Cosmos",
        "Creativity",
        "Crime",
        "CRISPR",
        "Crowdsourcing",
        "Culture",
        "Curiosity",
        "Cyborg",
        "Dance",
        "Dark matter",
        "Data",
        "Death",
        "Debate",
        "Decision-making",
        "Deextinction",
        "Demo",
        "Democracy",
        "Depression",
        "Design",
        "Development",
        "Dinosaurs",
        "Disability",
        "Disaster relief",
        "Discovery",
        "Disease",
        "DNA",
        "Driverless cars",
        "Drones",
        "Ebola",
        "Ecology",
        "Economics",
        "Education",
        "Egypt",
        "Empathy",
        "Energy",
        "Engineering",
        "Entertainment",
        "Entrepreneur",
        "Environment",
        "Europe",
        "Evil",
        "Evolution",
        "Exoskeleton",
        "Exploration",
        "Extraterrestrial life",
        "Extreme sports",
        "Failure",
        "Faith",
        "Family",
        "Farming",
        "Fashion",
        "Fear",
        "Feminism",
        "Film",
        "Finance",
        "Fish",
        "Flight",
        "Food",
        "Foreign Policy",
        "Forensics",
        "Friendship",
        "Funny",
        "Future",
        "Gaming",
        "Garden",
        "Gender",
        "Gender equality",
        "Gender spectrum",
        "Genetics",
        "Geology",
        "Glacier",
        "Global development",
        "Global issues",
        "Goal-setting",
        "God",
        "Google",
        "Government",
        "Grammar",
        "Green",
        "Guitar",
        "Hack",
        "Happiness",
        "Health",
        "Health care",
        "Hearing",
        "Heart health",
        "History",
        "HIV",
        "Human origins",
        "Humanity",
        "Humor",
        "Identity",
        "Illness",
        "Illusion",
        "Immigration",
        "India",
        "Industrial design",
        "Inequality",
        "Infrastructure",
        "Innovation",
        "Insects",
        "Intelligence",
        "Interface design",
        "Internet",
        "Interview",
        "Invention",
        "Investment",
        "Iran",
        "Iraq",
        "Islam",
        "Jazz",
        "Journalism",
        "Language",
        "Latin America",
        "Latin America",
        "Law",
        "Leadership",
        "LGBT",
        "Library",
        "Life",
        "Literature",
        "Live music",
        "Love",
        "MacArthur grant",
        "Machine learning",
        "Magic",
        "Manufacturing",
        "Map",
        "Marketing",
        "Mars",
        "Materials",
        "Math",
        "Media",
        "Medical imaging",
        "Medical research",
        "Medicine",
        "Meditation",
        "Meme",
        "Memory",
        "Men",
        "Mental health",
        "Microbes",
        "Microbiology",
        "Microfinance",
        "Microsoft",
        "Middle East",
        "Military",
        "Mind",
        "Mindfulness",
        "Mining",
        "Mission blue",
        "Mobility",
        "Molecular biology",
        "Money",
        "Monkeys",
        "Moon",
        "Morality",
        "Motivation",
        "Museums",
        "Music",
        "Nanoscale",
        "Narcotics",
        "NASA",
        "Natural disaster",
        "Natural resources",
        "Nature",
        "Neuroscience",
        "New York",
        "News",
        "Nobel prize",
        "Nonviolence",
        "Novel",
        "Nuclear energy",
        "Nuclear weapons",
        "Obesity",
        "Oceans",
        "Oil",
        "One Laptop Per Child",
        "Online video",
        "Open-source",
        "Origami",
        "Pain",
        "Painting",
        "Paleontology",
        "Pandemic",
        "Parenting",
        "Peace",
        "Performance",
        "Performance art",
        "Personal growth",
        "Personality",
        "Pharmaceuticals",
        "Philanthropy",
        "Philosophy",
        "Photography",
        "Physics",
        "Physiology",
        "Piano",
        "Planets",
        "Plants",
        "Plastic",
        "Play",
        "Poetry",
        "Policy",
        "Politics",
        "Pollution",
        "Population",
        "Potential",
        "Poverty",
        "Prediction",
        "Pregnancy",
        "Presentation",
        "Primates",
        "Prison",
        "Privacy",
        "Product design",
        "Productivity",
        "Programming",
        "Prosthetics",
        "Protests",
        "Psychology",
        "PTSD",
        "Public health",
        "Public spaces",
        "Race",
        "Refugees",
        "Relationships",
        "Religion",
        "Resources",
        "Robots",
        "Rocket science",
        "Sanitation",
        "Science",
        "Science and art",
        "Security",
        "Self",
        "Senses",
        "Sex",
        "Shopping",
        "Sight",
        "Simplicity",
        "Singer",
        "Skateboarding",
        "Slavery",
        "Sleep",
        "Smell",
        "Social change",
        "Social media",
        "Society",
        "Sociology",
        "Software",
        "Solar",
        "Solar energy",
        "Solar system",
        "Sound",
        "South America",
        "Space",
        "Speech",
        "Spoken word",
        "Sports",
        "State-building",
        "Statistics",
        "Storytelling",
        "Street art",
        "String theory",
        "Student",
        "Submarine",
        "Success",
        "Suicide",
        "Surgery",
        "Surveillance",
        "Sustainability",
        "Synthetic biology",
        "Teaching",
        "Technology",
        "Telecom",
        "Television",
        "Terrorism",
        "Testing",
        "Theater",
        "Time",
        "Toy",
        "Trafficking",
        "Transgender",
        "Transportation",
        "Travel",
        "Trees",
        "Trust",
        "Typography",
        "United States",
        "Universe",
        "Urban",
        "Urban planning",
        "Vaccines",
        "Violence",
        "Violin",
        "Virtual reality",
        "Virus",
        "Visualizations",
        "Vocals",
        "Vulnerability",
        "War",
        "Water",
        "Weather",
        "Web",
        "Wikipedia",
        "Wind energy",
        "Women",
        "Women in business",
        "Work",
        "Work-life balance",
        "World cultures",
        "Writing",
        "Wunderkind"

    };
}
